# Generated by Django 2.0.4 on 2018-05-11 04:01

from django.db import migrations, models


def populate_alliance_id_name(apps, schema_editor):
    EveCorporationInfo = apps.get_model('eveonline', 'EveCorporationInfo')
    for corp in EveCorporationInfo.objects.filter(_alliance__isnull=False).select_related('_alliance'):
        corp.alliance_id = corp._alliance.alliance_id
        corp.alliance_name = corp._alliance.alliance_name
        corp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evecorporationinfo',
            old_name='alliance',
            new_name='_alliance',
        ),
        migrations.AddField(
            model_name='evecorporationinfo',
            name='alliance_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='evecorporationinfo',
            name='alliance_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(populate_alliance_id_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='evecorporationinfo',
            name='_alliance',
        ),
    ]
