# Generated by Django 2.0.4 on 2018-05-10 21:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def validate_new_scopes(apps, schema_editor):
    CorpStats = apps.get_model('corputils', 'CorpStats')
    CorpStats.objects.exclude(token__scopes__name='esi-corporations.track_members.v1').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('corputils', '0005_cleanup_permissions'),
    ]

    operations = [
        migrations.RunPython(validate_new_scopes, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='corpstats',
            options={'permissions': (('view_corp_corpstats', 'Can view corp stats of their corporation.'), ('view_alliance_corpstats', 'Can view corp stats of members of their alliance.'), ('view_state_corpstats', 'Can view corp stats of members of their auth state.'), ('view_all_corpstats', 'Can view all corp stats.')), 'verbose_name': 'corp stats', 'verbose_name_plural': 'corp stats'},
        ),
        migrations.AddField(
            model_name='corpmember',
            name='alts',
            field=models.ManyToManyField(blank=True, related_name='alt_corpmembers', to='eveonline.EveCharacter'),
        ),
        migrations.AddField(
            model_name='corpmember',
            name='base_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpmember',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpmember',
            name='location_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpmember',
            name='location_name',
            field=models.CharField(blank=True, null=True, max_length=78),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpmember',
            name='logon_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpmember',
            name='logoff_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpmember',
            name='main_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCharacter'),
        ),
        migrations.AddField(
            model_name='corpmember',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpmember',
            name='ship_type_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpmember',
            name='ship_type_name',
            field=models.CharField(default='None', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpmember',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
